server:
  port: 9003
spring:
  application:
    name: eureka-register-service-3

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/,http://127.0.0.1:9002/eureka/  #其他注册服务
  server:
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
    renewal-percent-threshold: 0.49